In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
### Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”

fh = open("numbers.txt","w")

fh.write("Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”")

num1 = int(input("Enter your first number")) 
num2 = int(input("Enter your second number"))
num3 = int(input("Enter your third number"))
num4 = int(input("Enter your fourth number"))

fh.write(f"{num1} {num2} {num3} {num4}")
fh.close()

In [2]:
## Create a 1D array of numbers from 0 to 9
import numpy as np
x = np.arange(10)
print("Array from 0 to 9:")
print(x)

Array from 0 to 9:
[0 1 2 3 4 5 6 7 8 9]


In [4]:
## Create a 3×3 NumPy array of all Boolean value Trues
bool_arr = np.ones((3,3), dtype=bool)
print(bool_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
## Extract all odd numbers from array of 1-10
import numpy as np
a = np.array([1,2,3,4,5,6,6,7,7,8,9])
a[a % 2 == 1]

array([1, 3, 5, 7, 7, 9])

In [8]:
## Replace all odd numbers in an array of 1-10 with the value -1
import numpy as np 
 
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 
 
odd_values = (a%2 == 1) 

a[odd_values] = -1 
print(a)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [16]:
## Convert a 1D array to a 2D array with 2 rows
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2,5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
## Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals
a = np.arange (10,19).reshape (3,3) 
b = np.arange (19,28).reshape (3,3) 
c = np.dot(a, b)
sum = np.sum(c)
print(sum)


8748
